-
  name: Install packages using loop - with_items
  hosts: all
  vars:
    packages:
      - git
      - httpd
      - make
  become: yes
  become_method: sudo
  tasks:
    -
      name: install packages in loop
      yum:
        name: "{{item}}"
        state: present
      with_items:
          '{{packages}}'
